### Pega todos os usuários

GET http://localhost:3003/users

### Cria um usuário
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Dog",
    "email": "dog@gmail.com",
    "password": "${2318jhdasgf320}"
}

### Cria um produto
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "MacBook Air",
    "price": 6000,
    "imageUrl": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

