###
POST http://localhost:3003/usuarios
Content-Type: application/json

{ 
    "nome": "Beatriz Fraga",
    "cpf": "332.543.222.56",
    "dataDeNascimento": "16/02/2010"  
}

###
POST http://localhost:3003/usuarios
Content-Type: application/json

{ 
    "nome": "Beatriz Fraga",
    "cpf": "332.543.222.56",
    "dataDeNascimento": "16/02/1998"  
}

###
GET  http://localhost:3003/usuarios

###
GET  http://localhost:3003/usuarios/43354633212

###
POST  http://localhost:3003/usuarios/45254675406/Rengar/deposito
Content-Type: application/json

{
    "valor": 500
}

###
POST http://localhost:3003/usuarios/45254675406/pagamento
Content-Type: application/json

{
    "valor": 500
}

###
POST http://localhost:3003/usuarios/45254675406/pagamento
Content-Type: application/json

{
    "valor": 500,
    "data": "14/04/2022"
}

###
POST http://localhost:3003/usuarios/45254675406/pagamento
Content-Type: application/json

{
    "valor": 500,
    "data": "15/03/2022"
}

###
PUT http://localhost:3003/usuarios/45254675406/saldo


